name: tb_driver
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.1.0
  url_launcher: ^6.1.12
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^5.0.2

  # Icons
  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  lottie: ^3.1.0

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  device_preview: ^1.1.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/svg/
    - assets/logo/
    - assets/img/
    - assets/img/animations/
    - assets/img/on_boarding/
    - assets/img/banner/
    - assets/img/products/
    - assets/img/splash/
    - assets/img/background/
    - assets/img/profile/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: SansPro
      fonts:
        - asset: assets/fonts/PFBagueSansPro-Reg.ttf
        - asset: assets/fonts/PFBagueSansPro-Light.ttf
          weight: 400
        - asset: assets/fonts/PFBagueSansPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/PFBagueSansPro-Bold.ttf
          weight: 600
        - asset: assets/fonts/PFBagueSansPro-Black.ttf
          weight: 700
        - asset: assets/fonts/PFBagueSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/PFBagueSansPro-LightItalic.ttf
          style: italic
          weight: 500
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helveticanw.ttf
        - asset: assets/fonts/helvetica-narrow-bold.ttf
          weight: 700
