// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgphPtf5n_cJ5wte2cPBa0wU7VH4ibQl4',
    appId: '1:170460970342:web:91f597bd5243a848c49ca7',
    messagingSenderId: '170460970342',
    projectId: 'treeblazz-680ae',
    authDomain: 'treeblazz-680ae.firebaseapp.com',
    storageBucket: 'treeblazz-680ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLGwn3E0rtzGfYcglpYOTtxN9TOeRb7Rk',
    appId: '1:170460970342:android:ab568e402afcd757c49ca7',
    messagingSenderId: '170460970342',
    projectId: 'treeblazz-680ae',
    storageBucket: 'treeblazz-680ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPMZG4Uv8GXfdd_w9rCYfG-mnQyL8WFw',
    appId: '1:170460970342:ios:aac3e8d689969130c49ca7',
    messagingSenderId: '170460970342',
    projectId: 'treeblazz-680ae',
    storageBucket: 'treeblazz-680ae.appspot.com',
    androidClientId:
        '170460970342-b59celscpmo810lklsvgc95h6lathrm3.apps.googleusercontent.com',
    iosClientId:
        '170460970342-i0mk80v0slbtknoadfum2j36tlb7bkjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.treeBlazz01',
  );
}
